name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      - name: Run tests
        run: |
          cd frontend
          npm run test -- --coverage
      - name: Build
        run: |
          cd frontend
          npm run build
      - name: Lint
        run: |
          cd frontend
          npm run lint

  axe-audit:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      - name: Install Puppeteer browser
        run: npx puppeteer browsers install chrome
      - name: Start dev server
        run: |
          cd frontend
          npm run dev &
          echo $! > dev-server.pid
      - name: Wait for server to be ready
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:3000 > /dev/null 2>&1; do sleep 1; done'
      - name: Run axe accessibility audit
        run: |
          cd frontend
          npm run axe:puppeteer-ext > axe-results.json
      - name: Upload axe results
        uses: actions/upload-artifact@v4
        with:
          name: axe-audit-results
          path: frontend/axe-report.json
